# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeKitchen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeKitchen
  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher', '~> 3.0'
  pod 'LNSideMenu', '~> 2.3.2'
  pod 'CVCalendar', '~> 1.5.2'
end
